import type { Metadata } from "next";
import "./globals.css";
import { spaceGFont } from "@/fonts/spaceGFont";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${spaceGFont.variable}`}>
      <body className="text-black font-spaceG">{children}</body>
    </html>
  );
}
